name = "ConnectionPools"
uuid = "028224b0-1fcc-4ce4-9494-c68607c3a20e"
authors = ["Abraham Jaimes"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
